# Generated by Django 4.0.5 on 2022-07-09 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_memo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='icon_id',
            field=models.IntegerField(null=True, verbose_name='icon_id'),
        ),
        migrations.AddField(
            model_name='memo',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.memo', verbose_name='parent_id'),
        ),
    ]
