# Generated by Django 4.0.5 on 2022-07-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_memo_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_memo', to='api.memo', verbose_name='parent_id'),
        ),
    ]
